### PR TITLE
Merging in the Changes we made to get r2tree2 swerve working

### LINKED ISSUE #27: Tune heading and swerve wheel pid
also figure out why driving left does not work

### PR DESCRIPTION
**Pull request by noam987**
Tuned the PIDSs, got the swerve offsets and added a reset Gyro Method

### CODE REVIEW

File: code/src/main/java/frc/robot/subsystems/SwerveDrivetrain.java [hunk 1]
```diff
@@ -163,13 +171,15 @@ public void move(double x, double y, double theta, final boolean fieldRelative)
             this.m_pidController.setSetpoint((((this.m_gyro.getAngle() % 360) + 360) % 360));
             this.m_isTurning = false;
             theta = this.m_pidController.calculate((((this.m_gyro.getAngle() % 360) + 360) % 360));
-        } else {
+
+        }
+        else if (x != 0 && y!=0) {
```
Comment (thetaspirit) [inline code/src/main/java/frc/robot/subsystems/SwerveDrivetrain.java:178]: Be sure to state what this else-if block does, and why it's here

**Review by thetaspirit — APPROVED** [review]
